system/system/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.views.generic import TemplateView
from django.conf.urls import include
from django.contrib.auth import views
from ejournal.views import groupList, rating_log,group_study_raiting,group_visiting_raiting,group_addres_raiting,group_total_raiting,student_stat
from ejournal.views import groupDetailView, check_perm
from ejournal.views import groupUpdateView
from ejournal.views import save_student,DisciplineDetailView
from ejournal.views import groupCreateView,TeacherDetailView
from  ejournal.views import TeachersList, DisciplinesList, TeacherCreateView, TeacherEditView, TeacherDeleteView
from ejournal.views import groupDeleteView,DisciplineCreateView, DisciplineEditView, DisciplineDeleteView

urlpatterns = [
    path("admin/", admin.site.urls),
   # path("", groupList.as_view(), name='groups'),
    path('groups/', groupList.as_view(), name='groups'),
    path('teachers/', TeachersList.as_view(), name='teachers'),
    path('disciplines/', DisciplinesList.as_view(), name='disciplines'),
    re_path(r'^group/(?P<pk>\d+)$', groupDetailView.as_view(), name="group-detail"),
    re_path(r'^group-edit/(?P<pk>\d+)$', groupUpdateView.as_view(), name="group-edit" ),
    path('groups/create', groupCreateView.as_view(), name="group-create"),
    re_path(r'^group-delete/(?P<pk>\d+)$', groupDeleteView.as_view(), name="group-delete" ),
    path('teacher/create', TeacherCreateView.as_view(), name="teacher-create"),
    re_path(r'^teacher-edit/(?P<pk>\d+)$', TeacherEditView.as_view(), name="teacher-edit"),
    re_path(r'^teacher-detele/(?P<pk>\d+)$', TeacherDeleteView.as_view(), name="teacher-delete" ),
    re_path(r'^teacher/(?P<pk>\d+)$', TeacherDetailView.as_view(), name="teacher-detail"),
    path('discipline/create', DisciplineCreateView.as_view(), name="disсipline-create"),
    re_path(r'^discipline-edit/(?P<pk>\d+)$', DisciplineEditView.as_view(), name="discipline-edit"),
    re_path(r'^discipline-detele/(?P<pk>\d+)$', DisciplineDeleteView.as_view(), name="discipline-delete"),
    re_path(r'^discipline/(?P<pk>\d+)$', DisciplineDetailView.as_view(), name="discipline-detail"),
    path('group/rating/<int:pk>/', rating_log, name='rating'),
    path('group/group-study-rating/<int:pk>/', group_study_raiting, name='group-study-rating'),
    path('group/group-visiting-rating/<int:pk>/', group_visiting_raiting, name='group-visiting-rating'),
    path('group/group-addres-rating/<int:pk>/', group_addres_raiting, name='group-add-res-rating'),
    path('group/group-total-rating/<int:pk>/', group_total_raiting, name='group-total-rating'),
    path('', views.LoginView.as_view(), name="login"),
    path('accounts/', include('django.contrib.auth.urls')),
    path('student_stat/', student_stat, name="student_stat"),
    path('chech_perm/', check_perm, name="check_perm")
   # path('accounts/profile/', student_stat)


]

system/ejournal/models.py
from django.contrib.auth.models import User
from django.db import models
# Create your models here.
from django.urls import reverse


# модель Студент
class Student(models.Model):
    # surname - фамилия
    surname = models.CharField(max_length=80, verbose_name="фамилия")
    # name - имя
    name = models.CharField(max_length=80, verbose_name='имя')
    # patronymic - отчество
    patronymic = models.CharField(max_length=80, verbose_name='отчество')
    # group - учебная группа
    group = models.ForeignKey(to="StudentGroup", on_delete=models.CASCADE, verbose_name='учебная группа')

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['name', 'surname', 'patronymic'], name='unique fio student')
        ]
        ordering = ["surname", "name", "patronymic"]
        db_table = "student"

    def __str__(self):
        return self.surname + ' ' + self.name + ' ' + self.patronymic


# модель учебной группы
class StudentGroup(models.Model):
    # номер группы
    number = models.IntegerField(unique=True)
    # специлизация
    specialization = models.CharField(max_length=200)

    class Meta:
        ordering = ['number']
        db_table = "studentGroup"

    def __str__(self):
        return str(self.number)

    def get_absolute_url(self):
        return reverse('group-detail', args=[str(self.id)])

    def get_edit_url(self):
        return reverse('group-edit', args=[str(self.id)])

    def get_del_url(self):
        return reverse('group-delete', args=[str(self.id)])

    def get_rating_url(self):
        return reverse('rating', args=[str(self.id)])

    def get_study_rating_url(self):
        return reverse('group-study-rating', args=[str(self.id)])

    def get_visiting_rating_url(self):
        return reverse('group-visiting-rating', args=[str(self.id)])

    def get_add_res_rating_url(self):
        return reverse('group-add-res-rating', args=[str(self.id)])

    def get_total_rating(self):
        return reverse('group-total-rating', args=[str(self.id)])



# модель преподавателя
class Teacher(models.Model):
    # имя
    name = models.CharField(max_length=20, verbose_name="Имя")
    # фамилия
    surname = models.CharField(max_length=30, verbose_name="Фамилия")
    # отчество
    patronymic = models.CharField(max_length=30, verbose_name="Отчество")

    def __str__(self):
        return self.surname+" "+self.name

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['name', 'surname', 'patronymic'], name='unique fio teacher')
        ]
        ordering = ["surname", "name", "patronymic"]
        db_table = "teacher"

    def get_absolute_url(self):
        return reverse('teacher-detail', args=[str(self.id)])

    def get_edit_url(self):
        return reverse('teacher-edit', args=[str(self.id)])

    def get_del_url(self):
        return reverse('teacher-delete', args=[str(self.id)])


# модель Дисциплина
class Discipline(models.Model):
    TYPE_EXAM = [
        ('N', ''),
        ('Z', 'зачёт'),
        ('O', 'зачёт с оценкой'),
        ('E', 'экзамен')
    ]

    name = models.CharField(max_length=400, verbose_name="Название", unique=True)
    short_name = models.CharField(max_length=10, verbose_name="Аббревиатура", blank=True)
    teacher = models.ForeignKey(to="Teacher", on_delete=models.CASCADE, verbose_name="Преподаватель", blank=True,
                                null=True)
    course = models.IntegerField(verbose_name="Курс", blank=True, null=True)
    hours = models.IntegerField(verbose_name="Количество часов", blank=True, null=True)

    type_exam = models.CharField(max_length=1, choices=TYPE_EXAM, verbose_name="Тип экзамена")

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['name'], name='unique name discipline')
        ]
        ordering = ["name"]
        db_table = "discipline"

    def get_absolute_url(self):
        return reverse('discipline-detail', args=[str(self.id)])

    def get_edit_url(self):
        return reverse('discipline-edit', args=[str(self.id)])

    def get_del_url(self):
        return reverse('discipline-delete', args=[str(self.id)])


# модель оценки
class Mark(models.Model):
    student = models.ForeignKey(to="Student", on_delete=models.CASCADE, verbose_name="Студент")

    discipline = models.ForeignKey(to="GroupDiscipline", on_delete=models.CASCADE, verbose_name="Дисциплина")

    date = models.DateField(verbose_name="Дата")

    ball = models.IntegerField()

    class Meta:
        ordering = ["date", "student"]
        db_table = "mark"


# модель дисциплины группы
class GroupDiscipline(models.Model):
    group = models.ForeignKey(to="StudentGroup", on_delete=models.CASCADE, verbose_name="Взвод")
    discipline = models.ForeignKey(to="Discipline", on_delete=models.CASCADE, verbose_name="Дисциплина")

    class Meta:
        db_table = "groupDiscipline"

system/ejournal/views.py
from django.http import HttpResponse, HttpResponseRedirect, HttpResponsePermanentRedirect, Http404
from django.shortcuts import redirect, render
from django.template.response import TemplateResponse
from django.urls import reverse_lazy
from django.views import generic
from .forms import StudentForm
from .models import Student, StudentGroup, Teacher, Discipline, GroupDiscipline, Mark

def check_perm(request):
    if request.user.is_superuser:
        return redirect('../groups/')
    else:
        return redirect("/student_stat/")

def student_stat(request):
    surname = request.user.studentmodel.surname
    name = request.user.studentmodel.name
    patronymic = request.user.studentmodel.patronymic

    group = request.user.studentmodel.group
    disciplines = group.groupdiscipline_set.all()
    marks = Mark.objects.filter(discipline__in=disciplines, student=request.user.studentmodel)
    dates = marks.dates("date", "day")
    table = []
    title = ["Дисциплины"]
    for date in dates:
        title.append(str(date))
    for discipline in disciplines:
        dis_report = []
        dis_report.append(discipline.discipline.name)
        for date in dates:
            mark = marks.filter(date= date,discipline= discipline)[0]
            dis_report.append(mark.ball)
        table.append(dis_report)

    context = {"titles": title, "reports": table, "surname": surname, "name": name,"patronymic": patronymic, "group": group.number}
    return render(request, "student_info.html", context)

def group_study_raiting(request, pk):
    if request.method == "GET":
        group = StudentGroup.objects.get(id=pk)
        students = Student.objects.filter(group=group)
        discipline = Discipline.objects.get(name="дополнительные обязанности")
        group_disciplines = GroupDiscipline.objects.filter(group=group)
        group_disciplines = group_disciplines.exclude(discipline= discipline)
        raiting_list = []
        for student in students:
            cnt_ball = 0
            cur_ball = 0
            for discipline in group_disciplines:
                cur_marks = Mark.objects.filter(student=student, discipline=discipline)
                for mark in cur_marks:
                    if mark.ball != -1:
                        cnt_ball += 1
                        cur_ball += mark.ball
            cur_student = [str(student), cur_ball/cnt_ball]
            raiting_list.append(cur_student)
        raiting_list.sort(key=lambda x: x[1])
        raiting_list.reverse()
        raiting_list = map(lambda x: [x[0], float('%.2f'%x[1])], raiting_list)
        titles = ["ФИО", "Средная оценка"]
        context = {"students": raiting_list, "groupmodel": group, "titles": titles}
        return  render(request, "ejournal/group_raiting.html",context)

def group_visiting_raiting(request, pk):
    if request.method == "GET":
        group = StudentGroup.objects.get(id=pk)
        students = Student.objects.filter(group=group)
        group_disciplines = GroupDiscipline.objects.filter(group=group)
        raiting_list = []
        for student in students:
            cnt_pass = 0
            for discipline in group_disciplines:
                cur_marks = Mark.objects.filter(student=student, discipline=discipline)
                for mark in cur_marks:
                    if mark.ball == -1:
                        cnt_pass += 1
            cur_student = [student, cnt_pass]
            raiting_list.append(cur_student)
        raiting_list.sort(key=lambda x: x[1])
        #raiting_list = map(lambda x: x[0], raiting_list)
        titles = ["ФИО", "Количество пропусков"]
        context = {"students": raiting_list, "groupmodel": group, "titles": titles}
        return  render(request, "ejournal/group_raiting.html",context)

def group_addres_raiting(request, pk):
    if request.method == "GET":
        group = StudentGroup.objects.get(id=pk)
        students = Student.objects.filter(group=group)
        discipline = Discipline.objects.get(name="дополнительные обязанности")
        group_disciplines = GroupDiscipline.objects.filter(group=group, discipline=discipline)
        raiting_list = []
        for student in students:
            cur_ball = 0
            for discipline in group_disciplines:
                cur_marks = Mark.objects.filter(student=student, discipline=discipline)
                for mark in cur_marks:
                    if mark.ball != -1:
                        cur_ball += mark.ball
            cur_student = [student, cur_ball]
            raiting_list.append(cur_student)
        raiting_list.sort(key=lambda x: x[1])
        raiting_list.reverse()
        #raiting_list = map(lambda x: x[0], raiting_list)
        titles = ["ФИО", "Дополнительная активность"]
        context = {"students": raiting_list, "groupmodel": group, "titles": titles}
        return  render(request, "ejournal/group_raiting.html",context)

class Student_Stat():
    def __init__(self):
        self.fio = None
        self.study_ball = 0
        self.addres_ball = 0
        self.cnt_pass = 0

def group_total_raiting(request, pk):
    if request.method == "GET":
        group = StudentGroup.objects.get(id=pk)
        students = Student.objects.filter(group=group)
        discipline = Discipline.objects.get(name="дополнительные обязанности")
        group_disciplines = GroupDiscipline.objects.filter(group=group)
        group_disciplines_addres = group_disciplines.get(discipline=discipline)
        group_disciplines = group_disciplines.exclude(discipline=discipline)
        raiting_list = []
        for student in students:
            cnt_pass = 0
            cur_ball = 0
            addres_ball =0
            student_stat = Student_Stat()
            for discipline in group_disciplines:
                cur_marks = Mark.objects.filter(student=student, discipline=discipline)
                for mark in cur_marks:
                    if mark.ball != -1:
                        cur_ball += mark.ball
                    else:
                        cnt_pass += 1
            cur_marks = Mark.objects.filter(student=student, discipline=group_disciplines_addres)
            for mark in cur_marks:
                if mark.ball != -1:
                    addres_ball += mark.ball

            student_stat.addres_ball = addres_ball
            student_stat.study_ball =cur_ball
            student_stat.cnt_pass = cnt_pass
            student_stat.fio = str(student)
            raiting_list.append(student_stat)
        max_study =0
        max_addres =0
        max_pass =0
        for x in raiting_list:
            max_study = max(max_study, x.study_ball)
            max_addres = max(max_addres, x.addres_ball)
            max_pass = max(max_pass, x.cnt_pass)
        for x in raiting_list:
            x.study_ball = x.study_ball/max_study*60
            x.addres_ball = x.addres_ball/max_addres*25
            x.cnt_pass = (max_pass-x.cnt_pass)/max_pass*15
        raiting = []
        for x in raiting_list:
            raiting.append([x.fio, float('%.2f'%x.study_ball),float('%.2f'%x.addres_ball),
                            float('%.2f'%x.cnt_pass), float('%.2f'%(x.study_ball+x.addres_ball+x.cnt_pass))])
        raiting.sort(key= lambda x: x[1]+x[2]+x[3])
        raiting.reverse()
        titles = ["ФИО", "Баллы за учебу", "Баллы за доп активность","Баллы за посещение", "Суммарный балл"]
        context = {"students": raiting, "groupmodel": group, "titles": titles}
        return  render(request, "ejournal/group_raiting.html",context)



def rating_log(request, pk):
    if request.method == "GET":
        curDis = request.GET.get("choose_discipline")
        if curDis == None:
            group = StudentGroup.objects.get(id=pk)
            context = {"group": group}
            return render(request, "ejournal/raiting_log.html", context)
        else:
            discipline = Discipline.objects.get(name=curDis)
            group = StudentGroup.objects.get(id=pk)
            groupDiscipline = GroupDiscipline.objects.get(discipline=discipline, group=group)
            students = Student.objects.filter(group=group)
            curMarks = Mark.objects.filter(discipline=groupDiscipline)
            studentsMark =curMarks.filter(student__in=students)
            dates =set(curMarks.values_list('date',flat=True))
            strDate =sorted( list(map(lambda x: x.strftime("%Y-%m-%d"), dates)))
            marks = []
            for student in students:
                marks.append({"student": student, "marks":[]})
                for date in strDate:
                    if Mark.objects.filter(student=student, date=date,discipline=groupDiscipline).exists():
                        curMark = Mark.objects.get(student=student, date=str(date), discipline=groupDiscipline)
                        if curMark.ball == -1:
                            marks[-1]["marks"].append('н')
                        else:
                            marks[-1]["marks"].append(curMark.ball)
                    else:
                        marks[-1]["marks"].append(0)
            context = {"group": group, "students": students, "marks": curMarks, "dates": strDate, "stmarks": marks, "cur_discipline": discipline}

            return render(request, "ejournal/raiting_log.html", context)
    else:
        curDis = request.GET.get("choose_discipline")
        dates = request.POST.getlist("data")
        ocenkas = request.POST.getlist('ocenka')
        group = StudentGroup.objects.get(id=pk)
        discipline = Discipline.objects.get(name=curDis)
        groupDiscipline = GroupDiscipline.objects.get(discipline=discipline, group=group)
        students =list(Student.objects.filter(group=group))
        curMarks = Mark.objects.filter(discipline=groupDiscipline)
        studentsMark = curMarks.filter(student__in=students)
        studentsMark.delete()
        i =1
        j=0
        curStudent= students[j]
        for ocenka in ocenkas:
            if ocenka == '' or dates[i-1] == '':

system/ejournal/templates/firstapp/discipline_confirm_delete.html
{% extends 'base.html' %}
{% block content%}
<h1>Удаление дисциплины</h1>
    <form action="" method="post">{% csrf_token %}
      <p>Вы точно хотите удалить эту дисциплину "{{ dicsipline.name }}"?</p>
      <input type="submit" value="Потвердить" />
    </form>
{% endblock content %}

system/ejournal/templates/firstapp/discipline_create.html
{% extends 'base.html' %}
{% block content %}
    <h1>Дисциплина</h1>
    <form action="" method="post">{% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Сохранить" />
  </form>
{% endblock content%}

system/ejournal/templates/firstapp/discipline_detail.html
{% extends 'base.html' %}
{% block content %}
      <h1>Дисциплина</h1>
    <p><strong>Название: </strong><a>{{discipline.name}}</a></p>
    <p><strong>Аббревиатура:</strong><a>{{discipline.short_name}}</a></p>
    <p><strong>Кафедра: </strong><a>{{discipline.departament}}</a></p>
    <p><strong>Преподаватель: </strong><a>{{discipline.teacher}}</a></p>
    <p><strong>Курс: </strong><a>{{discipline.course}}</a></p>
    <p><strong>Часы: </strong><a>{{discipline.hours}}</a></p>
    <p><strong>Тип экзамена: </strong><a>{{discipline.get_type_exam_display}}</a></p>
<button onclick="location.href='{{discipline.get_edit_url}}'">Изменить дисциплину</button>
<button onclick="location.href='{{discipline.get_del_url}}'">Удалить дисциплину</button>
{% endblock %}

system/ejournal/templates/firstapp/discipline_list.html
{% extends 'base.html' %}
<title>Discipline</title>
{% block content %}
  <h1>Список дисциплин</h1>
  <div class="nav-right">
    <a href="{% url 'disсipline-create' %}">Добавить новую дисциплину</a><br>
  </div>
  {% if discipline_list %}
  <ul>
    {% for discipline in discipline_list %}
    {% if discipline.name != "дополнительные обязанности" %}
      <li>
        <a href="{{ discipline.get_absolute_url }}">{{ discipline.name }}</a>
      </li>
    {% endif %}
    {% endfor %}
  </ul>
  {% else %}
    <p>Дисциплины отсутствуют</p>
  {% endif %}
{% endblock %}

system/ejournal/templates/firstapp/raiting_log.html
{% extends 'base.html' %}

{% block content %}
<script src="https://code.jquery.com/jquery-3.6.0.js"></script>
<script src="../../../static/scripts/addrow.js"></script>
<style type="text/css">
    table {
        border-collapse: collapse;
    }

    table th,
    table td {
        border: 1px solid #000;
    }
    input[type=date]::-webkit-calendar-picker-indicator {
  opacity: 0;
}
::-webkit-calendar-picker-indicator{
    margin-left: -35px;
}
</style>

<form id="choose_dis" name="discipline">
<select id="discipline" name="choose_discipline">
    {% for discipline in group.groupdiscipline_set.all %}
    {% if discipline.discipline == cur_discipline%}
    <option selected>{{discipline.discipline.name}}</option>
    {% else %}
    <option>{{discipline.discipline.name}}</option>
    {% endif %}
    {% endfor %}
</select>
    <button type="submit">Выбрать дисциплину</button>
</form>

{% if students %}
<button id="addlesson" type="button">Добавить занятие</button>
<form action="" method="post">
{% csrf_token %}
<table id="marks"  name="marks">
    <tr id="hd"><th id="students">Студенты</th>
        {% for date in dates%}
        <th><input type="date" value="{{date}}" name="data"/></th>
        {% endfor %}
    </tr>
    {% for student in stmarks %}
    <tr>
        <td align="center" name="student">{{student.student}}</td>
    {% for j in student.marks %}
    <td align="center"><input value="{{j}}"  name="ocenka" size="2" maxlength="2"/></td>
    {% endfor %}
    </tr>
    {% endfor %}
</table>
 <input type="submit" value="Сохранить"/>
</form>

{% endif %}

{% endblock %}

system/ejournal/templates/firstapp/squadmodel_confirm_delete.html
{% extends 'base.html' %}
{% block content%}
<h1>Удаление взвода</h1>
    <form action="" method="post">{% csrf_token %}
      <p>Вы точно хотите удалить взвод "{{ groupmodel.number }}"?</p>
      <input type="submit" value="Потвердить" />
    </form>
{% endblock content %}

system/ejournal/templates/firstapp/squadmodel_create.html
{% extends 'base.html' %}
{% block content %}
<script src="https://code.jquery.com/jquery-3.6.0.js"></script>
<script src="../../../static/scripts/addrow.js"></script>
    <h1>group</h1>
    <form action="" method="post">{% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Сохранить" />
  </form>

{% endblock content %}

system/ejournal/templates/firstapp/squadmodel_detail.html
{% extends 'base.html' %}
{% block content %}
<h1>Номер взвода: {{groupmodel.number}}</h1>

<p><strong>Кафедра:</strong><a>{{groupmodel.departament}}</a></p>
<p><strong>Специальность:</strong><a>{{groupmodel.specialization}}</a></p>

<button onclick="location.href='{{groupmodel.get_rating_url}}'">Журнал оценок</button> <br>
<button onclick="location.href='{{groupmodel.get_study_rating_url}}'">Рейтинг студентов по успеваемости</button> <br>
<button onclick="location.href='{{groupmodel.get_visiting_rating_url}}'">Рейтинг студентов по посещяемости</button> <br>
<button onclick="location.href='{{groupmodel.get_add_res_rating_url}}'">Рейтинг студентов по исполнению дополнительных обязанностей</button> <br>
<button onclick="location.href='{{groupmodel.get_total_rating}}'">Общий рейтинг студентов</button> <br>

 <style type="text/css">
.tabs { width: 100%; padding: 0px; margin: 0 auto; }
.tabs>input { display: none; }
.tabs>div {
    display: none;
    padding: 12px;
    border: 1px solid #C0C0C0;
    background: #FFFFFF;
}
.tabs>label {
    display: inline-block;
    padding: 7px;
    margin: 0 -5px -1px 0;
    text-align: center;
    color: #666666;
    border: 1px solid #C0C0C0;
    background: #E0E0E0;
    cursor: pointer;
}
.tabs>input:checked + label {
    color: #000000;
    border: 1px solid #C0C0C0;
    border-bottom: 1px solid #FFFFFF;
    background: #FFFFFF;
}

    table {
        border-collapse: collapse;
    }

    table th,
    table td {
        border: 1px solid #000;
    }

#tab_1:checked ~ #students,
#tab_2:checked ~ #disciplines { display: block; }
</style>
<div class="tabs">
    <input type="radio" name="inset" value="" id="tab_1" checked>
    <label for="tab_1">Студенты</label>
    <input type="radio" name="inset" value="" id="tab_2">
    <label for="tab_2">Дисциплины</label>


    <div id="students">
        <div style="margin-left:20px;margin-top:20px">
            <h4>Студенты</h4>
            <table>
                <tbody>
                <tr>
                    <th>Фамилия</th>
                    <th>Имя</th>
                    <th>Отчество</th>
                </tr>
                {% for student in groupmodel.studentmodel_set.all %}
                <tr>
                    <td>{{student.surname}}</td>
                    <td>{{student.name}}</td>
                    <td>{{student.patronymic}}</td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

    <div id="disciplines">
        <div style="margin-left:20px;margin-top:20px">
            <h4>Дисциплины</h4>
            <table>
                <tbody>
                <tr>
                    <th>Название дисциплины</th>

                </tr>
                {% for discipline in groupmodel.groupdiscipline_set.all %}
                <tr>
                    <td>{{discipline.discipline.name}}</td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
<button onclick="location.href='{{groupmodel.get_edit_url}}'">Изменить взвод</button>
<button onclick="location.href='{{groupmodel.get_del_url}}'">Удалить взвод</button>
{% endblock %}

system/ejournal/templates/firstapp/squadmodel_list.html
{% extends 'base.html' %}
{% load static %}
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
<title>Взвода</title>
{% block content %}
  <h1>Список взводов</h1>
  <div class="nav-right">
    <a href="{% url 'group-create' %}">Добавить новый взвод</a><br>
  </div>
  {% if groupmodel_list %}
  <ul>
    {% for group in groupmodel_list %}
      <li>
        <a href="{{ group.get_absolute_url }}">{{ group.number }}</a>
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>Отсутствуют взвода</p>
  {% endif %}
{% endblock %}

system/ejournal/templates/firstapp/student_info.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>Система оценивания студентов ВУЦ</title>
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400"
    rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
  </head>

  <style type="text/css">
    table {
        border-collapse: collapse;
    }

    table th,
    table td {
        border: 1px solid #000;
    }
</style>

  <body>
    <div>
      <header>
        <div class="nav-left">
          <h1><a href="{% url 'groups' %}">Система оценивания студентов Вуц</a></h1>
        </div>

         <div class="nav-right">
          <a href="{% url 'logout' %}">Выйти из системы</a><br>
         </div>

      </header>
        <h1>Номер взвода: {{group}}</h1>

        <p><strong>Фамилия: </strong><a>{{surname}}</a></p>
        <p><strong>Имя: </strong><a>{{name}}</a></p>
        <p><strong>Отчество: </strong><a>{{patronymic}}</a></p>

        <table>
                <tbody>
                <tr>
                    {% for title in titles %}
                    <td align="center">{{title}}</td>
                    {% endfor %}
                </tr>
                {% for report in reports %}
                <tr>
                    {% for x in report %}
                    <td align="center">{{x}}</td>
                    {% endfor %}
                </tr>
                {% endfor %}
                </tbody>
            </table>

    </div>
  </body>
</html>

system/ejournal/templates/firstapp/teacher_confirm_delete.html
{% extends 'base.html' %}
{% block content%}
<h1>Удаление преподавателя</h1>
    <form action="" method="post">{% csrf_token %}
      <p>Вы точно хотите удалить этого преподователя "{{ teacher }}"?</p>
      <input type="submit" value="Потвердить" />
    </form>
{% endblock content %}

system/ejournal/templates/firstapp/teacher_create.html
{% extends 'base.html' %}
{% block content %}
    <h1>Преподаватель</h1>
    <form action="" method="post">{% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Сохранить" />
  </form>
{% endblock content%}

system/ejournal/templates/firstapp/teacher_list.html
{% extends 'base.html' %}
{% load static %}
<title>Преподаватели</title>
{% block content %}
  <h1>Список преподавателей</h1>
 <div class="nav-right">
    <a href="{% url 'teacher-create' %}">Добавить нового преподавателя</a><br>
  </div>
  {% if teacher_list %}
  <ul>
    {% for teacher in teacher_list %}
      <li>
        <a href="{{ teacher.get_absolute_url }}">{{ teacher }}</a>
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>Отсутсвуют преподаватели.</p>
  {% endif %}
{% endblock %}

system/ejournal/templates/firstapp/teacher_update.html
{% extends 'base.html' %}
{% block content %}
    <h1>Преподаватель</h1>
    <form action="" method="post">{% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Сохранить" />

  </form>

{% endblock content %}